import { JsonLd } from "./JsonLd";
import Image from "next/image";
import Link from "next/link";
import { Breadcrumbs } from "./PageHero";
import { NextStep, OfficialResources, RelatedGuides, ReviewedDate } from "./ContentTools";
import type { Guide } from "../data/guides";
import { SITE_URL } from "../lib/metadata";
import { countyProfiles } from "../data/counties";
import { ZipLookupForm } from "./ZipLookupForm";

const hubNames = { homeowners: "Homeowners", renters: "Renters", resources: "Resources" } as const;

export function GuideArticle({ guide }: { guide: Guide }) {
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "Article", headline: guide.h1, description: guide.description, datePublished: guide.published, dateModified: guide.reviewed, mainEntityOfPage: `${SITE_URL}${guide.path}`, author: { "@type": "Organization", name: "MoveIn", url: SITE_URL }, publisher: { "@type": "Organization", name: "MoveIn", url: SITE_URL } },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: SITE_URL }, { "@type": "ListItem", position: 2, name: hubNames[guide.section], item: `${SITE_URL}/${guide.section}` }, { "@type": "ListItem", position: 3, name: guide.h1, item: `${SITE_URL}${guide.path}` }] },
    ...(guide.faqs?.length ? [{ "@type": "FAQPage", mainEntity: guide.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }] : []),
  ] };
  return <main id="main-content"><JsonLd data={schema} /><div className="shell content-page"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: hubNames[guide.section], href: `/${guide.section}` }, { label: guide.h1 }]} /><header className="article-header"><span className="eyebrow">{guide.eyebrow}</span><h1>{guide.h1}</h1><p className="direct-answer">{guide.directAnswer}</p><ReviewedDate published={guide.published} reviewed={guide.reviewed} /></header>{guide.image ? <figure className="guide-image"><Image src={guide.image.src} alt={guide.image.alt} width={guide.image.width} height={guide.image.height} sizes="(max-width: 760px) 100vw, 920px" quality={88} /></figure> : null}<article className="guide-article">{guide.sections.map((section) => <section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.steps ? <ol>{section.steps.map((step) => <li key={step}>{step}</li>)}</ol> : null}</section>)}</article>{guide.faqs?.length ? <section className="guide-faq county-faq"><span className="eyebrow">Common questions</span><h2>Frequently asked questions</h2>{guide.faqs.map((faq) => <details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</section> : null}<OfficialResources resources={guide.sources} /><RelatedGuides paths={guide.related} />{guide.featuredZips?.length ? <section className="guide-featured-zips"><span className="eyebrow">Reviewed Florida examples</span><h2>Explore verified ZIP utility pages</h2><p>These are address-confirmation starting points, not ZIP-wide provider guarantees.</p><div>{guide.featuredZips.map((area) => <Link href={`/lookup/${area.zip}`} key={area.zip}><strong>{area.zip}</strong><span>{area.city}, Florida</span></Link>)}</div></section> : null}<section className="guide-lookup"><div><span className="eyebrow">Address starting point</span><h2>Find utility providers by ZIP code</h2><p>Use the ZIP result as a shortlist, then confirm internet and every other service for the complete address.</p><Link className="text-link" href="/resources/utility-setup">Open the complete utility setup hub</Link></div><ZipLookupForm compact context={guide.path} /></section><section className="guide-county-links"><div className="section-heading compact"><span className="eyebrow">Central Florida coverage</span><h2>Continue to a county utility guide</h2></div><div>{countyProfiles.map((county) => <Link href={`/${county.slug}`} data-analytics-county={county.name} key={county.name}>{county.name} County utilities</Link>)}</div></section><NextStep /><aside className="editorial-note"><p><strong>General information:</strong> Provider territories, requirements, contacts, and availability can change. Confirm the complete address with the official provider or government source. <a href={`/corrections`}>Report incorrect information</a>.</p></aside></div></main>;
}
