"use client";

import Link from "next/link";
import { useState } from "react";
import { internetProviders } from "../data/internet";
import { trackEvent } from "../lib/analytics";

export function MovingInternetChooser({ sourcePage = "/internet" }: { sourcePage?: string }) {
  const [answer, setAnswer] = useState<"yes" | "no" | null>(null);
  return <section className="moving-internet-tool"><div><span className="eyebrow">Moving your Internet</span><h2>Do you already have Internet service?</h2><p>Your answer changes the first useful step. MoveIn never collects the street address.</p><div><button type="button" aria-pressed={answer === "yes"} onClick={() => setAnswer("yes")}>Yes</button><button type="button" aria-pressed={answer === "no"} onClick={() => setAnswer("no")}>No</button></div></div>{answer === "yes" ? <div className="moving-internet-result"><h3>Check, compare, then schedule.</h3><ol><li>Check whether the current provider serves the complete new address.</li><li>Compare at least one alternative before transferring automatically.</li><li>Decide whether to transfer or switch based on technology, equipment, and timing.</li><li>Schedule activation, test the new connection, then close the old service when appropriate.</li></ol><div>{internetProviders.map((provider) => provider.movingOrTransferUrl ? <a href={provider.movingOrTransferUrl} target="_blank" rel="noopener noreferrer" onClick={() => trackEvent("internet_transfer_click", { provider: provider.providerName, technology: provider.technologyTypes.join(" | "), source_page: sourcePage })} key={provider.id}>{provider.providerName} official move guidance</a> : null)}</div><Link href="/internet/transfer-or-switch">Compare transferring versus switching</Link></div> : answer === "no" ? <div className="moving-internet-result"><h3>Build an address-qualified shortlist.</h3><ol><li>Enter the new ZIP to review possible providers.</li><li>Use each provider’s official checker for the complete address.</li><li>Compare wired and wireless options, equipment, and installation.</li><li>Schedule service and test it before relying on the connection.</li></ol><Link className="button" href="/internet/compare">Compare Internet options</Link></div> : null}</section>;
}
