import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Breadcrumbs, PageHero } from "../components/PageHero";
import { JsonLd } from "../components/JsonLd";
import { RelatedGuides } from "../components/ContentTools";
import { ZipLookupForm } from "../components/ZipLookupForm";
import { guidesFor } from "../data/guides";
import { pageMetadata, SITE_URL } from "../lib/metadata";

export const metadata: Metadata = pageMetadata("Utility Setup and Move-In Resources for Renters", "Learn how to confirm included utilities, open tenant accounts, arrange internet, document move-in condition, and save maintenance contacts.", "/renters");
const renterGuides = guidesFor("renters");
const renterLinks = [["Read the utility clauses", "Separate services included in rent from accounts the tenant must open.", "/renters/utility-responsibilities"], ["Set up tenant accounts", "Confirm electricity, water, gas, trash, and internet responsibility for the exact unit.", "/renters/set-up-utilities"], ["Plan internet installation", "Check unit-level availability and obtain permission for physical changes.", "/renters/internet-installation"], ["Find local collection information", "Confirm whether trash is handled by the city, county, landlord, or building.", "/resources/find-trash-service"]] as const;
export default function RentersPage() { const schema = { "@context": "https://schema.org", "@type": "CollectionPage", name: "MoveIn renter resources", url: `${SITE_URL}/renters`, hasPart: renterGuides.map((guide) => ({ "@type": "Article", name: guide.h1, url: `${SITE_URL}${guide.path}` })) }; return <main id="main-content"><JsonLd data={schema} /><div className="shell page-breadcrumb-wrap"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Renters" }]} /></div><PageHero eyebrow="Renters" title="Know what you set up—and what the lease covers." description="A concise renter hub for utility responsibility, installation rules, move-in records, and emergency contacts."><ZipLookupForm compact /></PageHero><section className="section"><div className="shell"><div className="section-heading"><span className="eyebrow">Start with the lease</span><h2>Turn the lease into a clear responsibility list.</h2><p>Do not assume a service is included. Confirm the provider for the exact unit and ask management about shared meters, building access, and required providers.</p></div><div className="topic-link-grid">{renterLinks.map(([title, description, href]) => <Link href={href} key={href}><h3>{title}</h3><p>{description}</p><span>Review this renter step <ArrowRight size={15} aria-hidden="true" /></span></Link>)}</div></div></section><section className="section subtle"><div className="shell guide-groups"><section><h2>Document move-in condition</h2><ul><li>Photograph rooms, fixtures, appliances, and existing damage.</li><li>Submit the condition report using the lease’s required method.</li><li>Photograph visible meter readings when appropriate.</li></ul></section><section><h2>Save the right contacts</h2><ul><li>Routine and emergency maintenance contacts.</li><li>Confirmed utility outage and emergency numbers.</li><li>Landlord or property-management notice address.</li></ul></section><section><h2>Confirm property rules</h2><ul><li>Internet installation and technician access.</li><li>Trash, recycling, parking, packages, and move-in access.</li><li>How utility charges are allocated in the building.</li></ul></section></div></section><section className="section"><div className="shell"><RelatedGuides paths={renterGuides.map((guide) => guide.path)} title="Renter guides" /></div></section></main>; }
