import type { Metadata } from "next";
import { Breadcrumbs, PageHero } from "../components/PageHero";
import { pageMetadata } from "../lib/metadata";

export const metadata: Metadata = pageMetadata("Privacy", "How MoveIn handles ZIP searches, correction submissions, request logs, analytics, and personal information.", "/privacy");

export default function PrivacyPage() {
  return <main id="main-content"><div className="shell page-breadcrumb-wrap"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Privacy" }]} /></div><PageHero eyebrow="Policy" title="Privacy" description="The ZIP lookup works without an account, email address, or street address." /><section className="section"><article className="shell prose"><p><strong>Last updated:</strong> August 3, 2026</p><h2>ZIP searches</h2><p>MoveIn does not save ZIP searches to its application database or associate them with a name or email. The web server and reverse proxy may retain ordinary short-lived request logs, including IP addresses, for security and operations. The lookup does not collect a street address.</p><h2>Coverage requests</h2><p>The Request My ZIP Code page does not ask for an email, name, phone number, account, or street address. When analytics is available, MoveIn sends the requested five-digit ZIP and the request page as an anonymous event so aggregate demand can guide future coverage. Invalid ZIP entries are not sent. Browser privacy controls or blocking tools may prevent the event.</p><h2>Corrections</h2><p>A correction requires a ZIP code, issue type, and description. Provider name, supporting URL, and reply email are optional. Reports are stored separately from verified provider records and never update public data automatically.</p><h2>Google Analytics</h2><p>MoveIn uses Google Analytics 4 to understand anonymous website usage. It measures page visits and interactions such as successful ZIP lookups, county and guide navigation, printable-resource use, requested unsupported ZIPs, and clicks to official provider information.</p><p>MoveIn does not send utility account information, exact street addresses, email addresses, submitted correction descriptions, or other correction-form content to Google Analytics. Successful lookup events use aggregate context such as county, state, coverage status, and provider-category count rather than the entered ZIP code. The only ZIP-specific custom event is an explicit unsupported-coverage request.</p><p>Visitors may use browser privacy controls, Global Privacy Control, Do Not Track, or content-blocking tools to limit analytics tracking. Analytics being unavailable never prevents the site or lookup from working.</p><h2>Other sensitive information</h2><p>MoveIn does not collect utility account credentials, Social Security numbers, identification documents, payment information, leases, or closing documents.</p><h2>Data sales</h2><p>MoveIn does not sell ZIP searches or personal information. Contact hello@movein.guide with privacy questions.</p></article></section></main>;
}
