import type { Metadata } from "next";
import { Breadcrumbs, PageHero } from "../components/PageHero";
import { pageMetadata } from "../lib/metadata";

export const metadata: Metadata = pageMetadata("Privacy", "How MoveIn handles My Move browser storage, ZIP searches, coverage requests, corrections, analytics, and personal information.", "/privacy");

export default function PrivacyPage() {
  return <main id="main-content"><div className="shell page-breadcrumb-wrap"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Privacy" }]} /></div><PageHero eyebrow="Policy" title="Privacy" description="The ZIP lookup and My Move work without an account, email address, or street address." /><section className="section"><article className="shell prose"><p><strong>Last updated:</strong> August 11, 2026</p>
    <h2>My Move browser storage</h2><p>My Move stores the move date, five-digit ZIP code, homeowner or renter selection, completed tasks, dismissed tasks, and tasks added from guides, and public Internet provider names saved to My Move in the current browser’s local storage. No account is required, and this data is not synced to MoveIn or another device. Clearing browser storage, using a private browsing session, or resetting My Move removes saved progress. If browser storage is blocked, the checklist can still work during the current visit but may not be available later.</p><p>MoveIn measures aggregate My Move interactions such as starting a checklist, completing a task category, adding a task, resetting, printing, or viewing a move phase. MoveIn does not send the move date, checklist text, notes, exact street address, names, account information, or other personally identifying checklist details to Google Analytics.</p>
    <h2>Saved Internet comparisons</h2><p>The Internet comparison tool can store up to four public provider names, technology labels, official links, review dates, and an optional five-digit ZIP in this browser. It does not store a street address, email, phone number, provider account, price, or personal note. The list is not synced to MoveIn and can be cleared from the comparison page or with browser controls.</p><h2>ZIP searches</h2><p>MoveIn does not save ZIP searches to its application database or associate them with a name or email. The web server and reverse proxy may retain ordinary short-lived request logs, including IP addresses, for security and operations. The lookup does not collect a street address.</p>
    <h2>Coverage requests</h2><p>The Request My ZIP Code page does not ask for an email, name, phone number, account, or street address. When analytics is available, MoveIn sends the requested five-digit ZIP and the request page as an anonymous event so aggregate demand can guide future coverage. Invalid ZIP entries are not sent. Browser privacy controls or blocking tools may prevent the event.</p>
    <h2>Corrections</h2><p>A correction requires a ZIP code, issue type, and description. Provider name, supporting URL, and reply email are optional. Reports are stored separately from verified provider records and never update public data automatically.</p>
    <h2>Google Analytics</h2><p>MoveIn uses Google Analytics 4 to understand aggregate website usage. It measures page visits and interactions such as successful ZIP lookups, county and guide navigation, printable use, My Move task categories, unsupported ZIP requests, renter guide and kit views, calculator starts and completions, and clicks to official provider information.</p><p>The move-in calculator does not save entered dollar amounts or send them to Analytics. Renter events use only public route names, coarse task categories, audience type, and counts such as the number of expense categories used. MoveIn does not send rent, deposit, fee, insurance, or moving amounts; lease details; utility account information; exact street addresses; email addresses; move dates; complete checklist text; notes; submitted correction descriptions; or other correction-form content to Google Analytics. Successful lookup events use aggregate context such as county, state, coverage status, and provider-category count rather than the entered ZIP code. The only ZIP-specific custom event is an explicit unsupported-coverage request.</p><p>Visitors may use browser privacy controls, Global Privacy Control, Do Not Track, or content-blocking tools to limit analytics tracking. Analytics being unavailable never prevents the site, lookup, calculator, printables, or My Move from working.</p>
    <h2>Other sensitive information</h2><p>MoveIn does not collect utility account credentials, Social Security numbers, identification documents, payment information, leases, closing documents, My Move notes, or home inventory records.</p><h2>Data sales</h2><p>MoveIn does not sell ZIP searches or personal information. Contact hello@movein.guide with privacy questions.</p>
  </article></section></main>;
}
