import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building2, Cable, CalendarClock, CheckCircle2, Construction, RadioTower, Router } from "lucide-react";
import { JsonLd } from "../components/JsonLd";
import { PageHero, Breadcrumbs } from "../components/PageHero";
import { ZipLookupForm } from "../components/ZipLookupForm";
import { InternetProviderCard } from "../components/InternetProviderCard";
import { SavedInternetOptions } from "../components/SavedInternetOptions";
import { MovingInternetChooser } from "../components/MovingInternetChooser";
import { InternetAnalytics } from "../components/InternetAnalytics";
import { internetProviders, internetZipRelationships, technologyLabel } from "../data/internet";
import { pageMetadata, SITE_URL } from "../lib/metadata";

export const metadata: Metadata = pageMetadata("Find Internet Providers for Your New Address", "Use a ZIP code to discover and compare possible wired and wireless home Internet providers, then confirm each option for the exact address.", "/internet");
const faqs = [
  ["How do I find Internet providers at my address?", "Use a ZIP search to build a shortlist, then check the complete address with each provider and the FCC National Broadband Map."],
  ["Can two homes in the same ZIP have different providers?", "Yes. Network routes, building wiring, capacity, and unit-level serviceability can produce different options within one ZIP."],
  ["How do I know whether AT&T Fiber is available?", "Run AT&T's official address check and confirm that the returned technology is fiber. A market page or nearby network does not prove fiber reaches the home."],
  ["Can I get T-Mobile or Verizon Home Internet?", "Both require an exact-address eligibility check. Signal, network capacity, and building conditions can change the answer."],
  ["Does Spectrum serve every address in a listed ZIP?", "No. MoveIn shows a market-supported possibility, not a ZIP-wide guarantee. Use Spectrum's address checker."],
  ["Should I check more than one provider?", "Yes. Checking multiple providers reveals alternative technologies, installation options, and regular terms that the first familiar provider may not offer."],
  ["When should I schedule installation?", "Check lead time after the move date is firm. Keep old service until the new connection works when practical and important for work, school, or access."],
  ["Can renters choose their own provider?", "Often, but a lease, included service, building wiring, technician access, or restrictions on physical changes can affect the choice."],
];

export default function InternetPage() {
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "WebPage", name: "Find Internet Providers for Your New Address", url: `${SITE_URL}/internet`, description: metadata.description },
    { "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: SITE_URL }, { "@type": "ListItem", position: 2, name: "Internet", item: `${SITE_URL}/internet` }] },
  ] };
  return <main id="main-content"><JsonLd data={schema} /><InternetAnalytics view="hub" /><div className="shell page-breadcrumb-wrap"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Internet" }]} /></div><PageHero eyebrow="Independent Internet comparison" title="Find the options—not just the first provider you recognize." description="Enter a ZIP to identify providers that may serve the area. Then check the exact address with every realistic option."><ZipLookupForm compact context="/internet" /></PageHero>
    <section className="section"><div className="shell"><SavedInternetOptions /><div className="internet-principle"><Router aria-hidden="true" /><div><span className="eyebrow">Two different questions</span><h2>ZIP lookup finds possibilities. Address checkers confirm service.</h2><p>MoveIn never claims a provider serves every home in a ZIP, submits your address, ranks a paid partner first, or reproduces temporary prices.</p></div><Link className="button" href="/internet/compare">Compare by ZIP <ArrowRight size={16} aria-hidden="true" /></Link></div></div></section>
    <section className="section subtle"><div className="shell"><div className="section-heading"><span className="eyebrow">Provider options</span><h2>Start with both wired and wireless possibilities.</h2><p>Providers are alphabetized. A card appearing here does not establish service at an address.</p></div><div className="internet-provider-grid">{internetProviders.toSorted((a, b) => a.providerName.localeCompare(b.providerName)).map((provider) => <InternetProviderCard key={provider.id} sourcePage="/internet" provider={{ slug: provider.id, name: provider.providerName, technologyTypes: provider.technologyTypes.map(technologyLabel), technologyType: provider.technologyTypes.map(technologyLabel).join(" | "), addressCheckUrl: provider.availabilityCheckerUrl, movingOrTransferUrl: provider.movingOrTransferUrl, officialWebsite: provider.officialWebsite, coverageLabel: "Address check required", coverageNotes: provider.notes, lastVerifiedAt: provider.sourceCheckedAt }} />)}</div></div></section>
    <section className="section"><div className="shell internet-explainer-grid"><article><Cable aria-hidden="true" /><h2>Wired Internet</h2><p>Fiber, cable, and DSL use physical infrastructure. Confirm the technology that reaches the residence—not merely the neighborhood or building.</p></article><article><RadioTower aria-hidden="true" /><h2>Wireless home Internet</h2><p>5G, LTE, and other fixed wireless connections use radio networks. Address eligibility, capacity, signal, and placement matter.</p></article><article><CheckCircle2 aria-hidden="true" /><h2>How to compare</h2><p>Compare the orderable technology, regular terms, equipment, installation, support, and provider-confirmed availability. Ignore “best” labels.</p></article></div></section>
    <section className="section subtle"><div className="shell"><MovingInternetChooser /></div></section>
    <section className="section"><div className="shell internet-timeline"><div><span className="eyebrow">Setup timeline</span><h2>Plan around access and installation—not a marketing promise.</h2></div><ol><li><CalendarClock aria-hidden="true" /><div><strong>As soon as the move date is firm</strong><span>Check the current provider and at least one alternative.</span></div></li><li><Building2 aria-hidden="true" /><div><strong>Before booking</strong><span>Confirm renter, HOA, or building access and wiring rules.</span></div></li><li><Construction aria-hidden="true" /><div><strong>Before move-in</strong><span>Schedule equipment or a technician and ask about new-construction serviceability.</span></div></li><li><CheckCircle2 aria-hidden="true" /><div><strong>After activation</strong><span>Test the connection and return old equipment when required.</span></div></li></ol></div></section>
    <section className="section subtle"><div className="shell internet-links"><div className="section-heading"><span className="eyebrow">Internet guides</span><h2>Continue with the question you actually have.</h2></div><div><Link href="/resources/find-internet-providers">Find providers at an address</Link><Link href="/resources/check-internet-availability">Check address availability</Link><Link href="/resources/fiber-internet-availability">Check fiber availability</Link><Link href="/resources/transfer-internet-when-moving">Transfer Internet when moving</Link><Link href="/renters/internet-installation">Apartment Internet setup</Link><Link href="/resources/printables/internet-setup-checklist">Internet setup checklist</Link></div></div></section>
    <section className="section"><div className="shell county-faq"><span className="eyebrow">Internet FAQ</span><h2>Questions movers ask before ordering.</h2>{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    <section className="section final-lookup"><div className="shell"><div><span className="eyebrow">Current pilot</span><h2>{internetZipRelationships.length} reviewed provider-and-ZIP possibilities across five Central Florida counties.</h2><p>Every relationship is a starting point and every address must still be checked.</p></div><ZipLookupForm compact context="/internet/footer" /></div></section>
  </main>;
}
