import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Icon } from "../components/Icon";
import { JsonLd } from "../components/JsonLd";
import { LocalResourceCards } from "../components/LocalResourceCards";
import { Breadcrumbs, PageHero } from "../components/PageHero";
import { ZipLookupForm } from "../components/ZipLookupForm";
import { countyResources, regionalCommunityResources, statewideMoveResources } from "../data/local-resources";
import { pageMetadata } from "../lib/metadata";
import { SITE_URL } from "../lib/metadata";

export const metadata: Metadata = pageMetadata("Find Utilities and Local Services by ZIP Code", "Use a Florida ZIP code to find possible electric, water, sewer, internet, trash, outage, city, and county information.", "/learn-your-area");
const available = [["Zap", "Electricity", "Possible electric providers, customer contacts, and outage actions."], ["Droplets", "Water and sewer", "Municipal, regional, private, well, or septic starting points."], ["Wifi", "Internet", "Official address-level broadband availability tools."], ["Recycle", "Trash and recycling", "City, county, HOA, landlord, or private collection context."], ["Landmark", "City and county", "Jurisdiction notes and official local-government resources."]];
const guideLinks = [["Find your electric company", "/resources/find-electric-company"], ["Find your water and sewer provider", "/resources/find-water-provider"], ["Check internet availability by address", "/resources/find-internet-providers"], ["Find trash and recycling information", "/resources/find-trash-service"]] as const;
const countyStartingPoints = Object.values(countyResources).map((profile) => profile.residentServices);
export default function LearnAreaPage() { const schema = { "@context": "https://schema.org", "@type": "CollectionPage", name: "Learn Your Area", url: `${SITE_URL}/learn-your-area`, description: metadata.description, hasPart: guideLinks.map(([label, href]) => ({ "@type": "WebPage", name: label, url: `${SITE_URL}${href}` })) }; return <main id="main-content"><JsonLd data={schema} /><div className="shell page-breadcrumb-wrap"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Learn Your Area" }]} /></div><PageHero eyebrow="Local starting points" title="Learn the services connected to your ZIP." description="A ZIP code provides a useful shortlist; the exact address determines many service and jurisdiction answers."><ZipLookupForm /></PageHero><section className="section"><div className="shell"><div className="simple-grid">{available.map(([icon, title, description]) => <article className="info-card" key={title}><span className="service-icon"><Icon name={icon} /></span><h2>{title}</h2><p>{description}</p></article>)}</div></div></section><section className="section subtle"><div className="shell"><div className="section-heading"><span className="eyebrow">After the utility accounts</span><h2>Update the records and safety information tied to your move.</h2><p>Use official systems for mail, driver and vehicle records, voter registration, flood maps, and Florida disaster planning.</p></div><LocalResourceCards resources={statewideMoveResources} /></div></section><section className="section"><div className="shell"><div className="section-heading"><span className="eyebrow">Five-county pilot</span><h2>Start with the county that serves the property.</h2><p>County portals connect new residents to libraries, parks, waste and recycling, roads, permits, emergency management, and community programs. City services may still apply inside municipal limits.</p></div><LocalResourceCards resources={countyStartingPoints} /></div></section><section className="section subtle"><div className="shell"><div className="section-heading"><span className="eyebrow">Schools and transportation</span><h2>Go directly to the regional agency or school district.</h2><p>Routes, fares, enrollment, attendance boundaries, and eligibility can change. Confirm the exact address and current instructions with the official organization.</p></div><LocalResourceCards resources={regionalCommunityResources} /></div></section><section className="section"><div className="shell"><div className="section-heading"><span className="eyebrow">Understand the result</span><h2>Use the right guide for the service.</h2></div><div className="topic-link-grid">{guideLinks.map(([label, href]) => <Link href={href} key={href}><h3>{label}</h3><p>Understand the limitation, then continue to the official provider or government source.</p><span>Read {label.toLowerCase()} <ArrowRight size={15} aria-hidden="true" /></span></Link>)}</div></div></section></main>; }
