import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Icon } from "../components/Icon";
import { Breadcrumbs, PageHero } from "../components/PageHero";
import { ZipLookupForm } from "../components/ZipLookupForm";
import { pageMetadata } from "../lib/metadata";

export const metadata: Metadata = pageMetadata("Find Utilities and Local Services by ZIP Code", "Use a Florida ZIP code to find possible electric, water, sewer, internet, gas, trash, outage, city, and county information.", "/learn-your-area");
const available = [["Zap", "Electricity", "Possible electric providers, customer contacts, and outage actions."], ["Droplets", "Water and sewer", "Municipal, regional, private, well, or septic starting points."], ["Wifi", "Internet", "Official address-level broadband availability tools."], ["Recycle", "Trash and recycling", "City, county, HOA, landlord, or private collection context."], ["Flame", "Natural gas", "Possible service only where official evidence supports it."], ["Landmark", "City and county", "Jurisdiction notes and official local-government resources."]];
const guideLinks = [["Find your electric company", "/resources/find-electric-company"], ["Find your water and sewer provider", "/resources/find-water-provider"], ["Check internet availability by address", "/resources/find-internet-providers"], ["Find trash and recycling information", "/resources/find-trash-service"]] as const;
export default function LearnAreaPage() { return <main id="main-content"><div className="shell page-breadcrumb-wrap"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Learn Your Area" }]} /></div><PageHero eyebrow="Local starting points" title="Learn the services connected to your ZIP." description="A ZIP code provides a useful shortlist; the exact address determines many service and jurisdiction answers."><ZipLookupForm /></PageHero><section className="section"><div className="shell"><div className="simple-grid">{available.map(([icon, title, description]) => <article className="info-card" key={title}><span className="service-icon"><Icon name={icon} /></span><h2>{title}</h2><p>{description}</p></article>)}</div></div></section><section className="section subtle"><div className="shell"><div className="section-heading"><span className="eyebrow">Understand the result</span><h2>Use the right guide for the service.</h2></div><div className="topic-link-grid">{guideLinks.map(([label, href]) => <Link href={href} key={href}><h3>{label}</h3><p>Understand the limitation, then continue to the official provider or government source.</p><span>Read {label.toLowerCase()} <ArrowRight size={15} aria-hidden="true" /></span></Link>)}</div></div></section></main>; }
